debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.campus.board project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  application.name: board-project
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: yys
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto : create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
